// obsidian-canvas-learning/src/components/canvas/RecommendationBar.svelte
<script lang="ts">
  /**
   * Canvas Learning System - Recommendation Bar Component
   * Story 1.7: Concept-relation recommendation UI (AC-3, AC-4, AC-5)
   *
   * A non-modal bottom bar showing concept relation recommendations.
   * Can be collapsed to a single line or expanded to show details.
   */

  import type { Recommendation } from '../../types/canvas';

  let {
    recommendations,
    onaccept,
    ondismiss,
    onclose,
  }: {
    recommendations: Recommendation[];
    onaccept: (recId: string) => void;
    ondismiss: (recId: string) => void;
    onclose: () => void;
  } = $props();

  let expanded = $state(false);

  function expand() {
    expanded = true;
  }

  function collapse() {
    expanded = false;
  }
</script>

{#if recommendations.length > 0}
  <div class="cl-canvas-recommendation-bar" class:cl-canvas-recommendation-bar--expanded={expanded}>
    {#if !expanded}
      <!-- Collapsed state -->
      <div class="cl-canvas-recommendation-collapsed">
        <span class="cl-canvas-recommendation-badge">{recommendations.length}</span>
        <span>发现 {recommendations.length} 条可能的概念关联</span>
        <button class="cl-canvas-recommendation-expand-btn" onclick={expand}>展开</button>
        <button class="cl-canvas-recommendation-close-btn" onclick={onclose} title="关闭">&times;</button>
      </div>
    {:else}
      <!-- Expanded state -->
      <div class="cl-canvas-recommendation-header">
        <span class="cl-canvas-recommendation-title">概念关联推荐</span>
        <button class="cl-canvas-recommendation-collapse-btn" onclick={collapse}>收起</button>
        <button class="cl-canvas-recommendation-close-btn" onclick={onclose} title="关闭">&times;</button>
      </div>
      <div class="cl-canvas-recommendation-list">
        {#each recommendations as rec (rec.id)}
          <div class="cl-canvas-recommendation-item">
            <span class="cl-canvas-recommendation-nodes">
              {rec.sourceNodeTitle} &#x2194; {rec.targetNodeTitle}
            </span>
            <span class="cl-canvas-recommendation-reason">{rec.reason}</span>
            <button
              class="cl-canvas-recommendation-accept"
              onclick={() => onaccept(rec.id)}
            >
              接受
            </button>
            <button
              class="cl-canvas-recommendation-dismiss"
              onclick={() => ondismiss(rec.id)}
            >
              忽略
            </button>
          </div>
        {/each}
      </div>
    {/if}
  </div>
{/if}

<style>
  .cl-canvas-recommendation-bar {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background: var(--background-secondary);
    border-top: 1px solid var(--background-modifier-border);
    z-index: 50;
    font-size: 13px;
    color: var(--text-normal);
  }

  .cl-canvas-recommendation-collapsed {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px;
  }

  .cl-canvas-recommendation-badge {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 20px;
    height: 20px;
    background: var(--interactive-accent);
    color: var(--text-on-accent);
    border-radius: 10px;
    font-size: 11px;
    font-weight: 600;
    padding: 0 6px;
  }

  .cl-canvas-recommendation-header {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px;
    border-bottom: 1px solid var(--background-modifier-border);
  }

  .cl-canvas-recommendation-title {
    flex: 1;
    font-weight: 600;
  }

  .cl-canvas-recommendation-list {
    max-height: 200px;
    overflow-y: auto;
  }

  .cl-canvas-recommendation-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px;
    border-bottom: 1px solid var(--background-modifier-border-hover, var(--background-modifier-border));
  }

  .cl-canvas-recommendation-item:last-child {
    border-bottom: none;
  }

  .cl-canvas-recommendation-nodes {
    font-weight: 500;
    flex-shrink: 0;
  }

  .cl-canvas-recommendation-reason {
    flex: 1;
    color: var(--text-muted);
    font-size: 12px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .cl-canvas-recommendation-accept,
  .cl-canvas-recommendation-dismiss {
    padding: 2px 8px;
    font-size: 12px;
    border: 1px solid var(--background-modifier-border);
    border-radius: var(--radius-s, 4px);
    cursor: pointer;
    background: var(--background-primary);
    color: var(--text-normal);
    flex-shrink: 0;
  }

  .cl-canvas-recommendation-accept:hover {
    background: var(--interactive-accent);
    color: var(--text-on-accent);
    border-color: var(--interactive-accent);
  }

  .cl-canvas-recommendation-dismiss:hover {
    background: var(--background-modifier-hover);
  }

  .cl-canvas-recommendation-expand-btn,
  .cl-canvas-recommendation-collapse-btn {
    padding: 2px 8px;
    font-size: 12px;
    border: 1px solid var(--background-modifier-border);
    border-radius: var(--radius-s, 4px);
    cursor: pointer;
    background: var(--background-primary);
    color: var(--text-normal);
    margin-left: auto;
  }

  .cl-canvas-recommendation-close-btn {
    padding: 2px 6px;
    font-size: 16px;
    line-height: 1;
    border: none;
    background: none;
    color: var(--text-muted);
    cursor: pointer;
  }

  .cl-canvas-recommendation-close-btn:hover {
    color: var(--text-normal);
  }
</style>

// frontend/src/components/RecommendationBar.tsx
import { useState } from 'react';
import type { Recommendation } from '../services/api-client';

interface RecommendationBarProps {
  recommendations: Recommendation[];
  loading: boolean;
  onAccept: (rec: Recommendation) => void;
  onDismiss: (rec: Recommendation) => void;
}

export function RecommendationBar({
  recommendations,
  loading,
  onAccept,
  onDismiss,
}: RecommendationBarProps) {
  const [collapsed, setCollapsed] = useState(false);

  // Hide completely when nothing to show and not loading
  if (recommendations.length === 0 && !loading) return null;

  return (
    <div className="absolute bottom-4 left-4 right-4 z-30 bg-white rounded-lg border border-gray-200 shadow-lg">
      {/* Header */}
      <div
        className="flex items-center justify-between px-4 py-2.5 cursor-pointer select-none"
        onClick={() => setCollapsed((c) => !c)}
      >
        <div className="flex items-center gap-2">
          <span className="text-sm text-yellow-600">&#128161;</span>
          <span className="text-sm font-medium text-gray-700">
            {loading
              ? '正在分析概念关联...'
              : `发现 ${recommendations.length} 组概念可能有关联`}
          </span>
        </div>
        <button
          className="text-xs text-gray-400 hover:text-gray-600 px-2 py-1"
          onClick={(e) => {
            e.stopPropagation();
            setCollapsed((c) => !c);
          }}
        >
          {collapsed ? '展开' : '折叠'}
        </button>
      </div>

      {/* Body */}
      {!collapsed && (
        <div className="px-4 pb-3 space-y-2 max-h-48 overflow-y-auto">
          {loading && recommendations.length === 0 && (
            <div className="flex items-center gap-2 py-2">
              <span className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-blue-500 border-t-transparent" />
              <span className="text-sm text-gray-500">分析中...</span>
            </div>
          )}

          {recommendations.map((rec) => (
            <div
              key={rec.id}
              className="flex items-center justify-between p-2.5 bg-gray-50 rounded-lg"
            >
              <div className="flex-1 min-w-0 mr-3">
                <div className="flex items-center gap-2 text-sm">
                  <span className="font-medium text-gray-800 truncate">{rec.sourceNodeTitle}</span>
                  <span className="text-gray-400 shrink-0">&harr;</span>
                  <span className="font-medium text-gray-800 truncate">{rec.targetNodeTitle}</span>
                  <span className="text-xs text-blue-500 font-medium shrink-0">
                    {Math.round(rec.confidence * 100)}%
                  </span>
                </div>
                <p className="text-xs text-gray-500 mt-0.5 truncate">{rec.reason}</p>
              </div>

              <div className="flex items-center gap-2 shrink-0">
                <button
                  onClick={() => onAccept(rec)}
                  className="px-3 py-1 text-xs font-medium text-green-700 bg-green-50 border border-green-200 rounded hover:bg-green-100 transition-colors"
                >
                  接受连线
                </button>
                <button
                  onClick={() => onDismiss(rec)}
                  className="px-3 py-1 text-xs font-medium text-gray-500 bg-gray-100 border border-gray-200 rounded hover:bg-gray-200 transition-colors"
                >
                  忽略
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
