// frontend/src/components/ChatPanel.tsx
/**
 * ChatPanel — AI conversation panel with streaming and persistent history.
 * Story 3-3: Chat Panel UI + Streaming
 * Story 3-9: Engine Fallback (engine status indicator)
 * Story 3-10: Quota Management (QuotaExhaustedBanner)
 * Story 3-11: Crash Recovery (RecoveryBanner)
 * Story 4-1: Edge Dialog Trigger — edge mode rendering
 * Story 4-2: Edge Dialog Agent Reasoning — edge-specific system prompt
 *
 * Features:
 * - Per-node conversation history persisted in Dexie (AC-4)
 * - Real-time streaming with typewriter effect via ClaudeEngine (AC-2)
 * - Markdown rendering for AI responses via react-markdown (AC-3)
 * - Auto-scroll to latest message
 * - Lazy loading: initial 50 messages, IntersectionObserver for older (AC-4)
 * - 2s first-token timeout with "Thinking..." indicator (AC-6)
 * - Input bar with Enter/Shift+Enter/Escape shortcuts (AC-5)
 * - Text selection toolbar for Add Tip / Pull to Node
 * - Engine status indicator (Claude Code vs API Key) (Story 3-9)
 * - Quota exhaustion banner with countdown + degradation options (Story 3-10)
 * - Crash recovery banner with auto/manual retry status (Story 3-11)
 * - Edge dialog mode: header shows "A <-> B", edge-specific system prompt (Story 4-1/4-2)
 *
 * Callers:
 * - App.tsx renders this in the right sidebar when a node or edge is selected
 *
 * Wiring:
 * - useChatStore (Zustand) — all message state + streaming actions
 * - MessageBubble — individual message rendering
 * - InputBar — text input with keyboard shortcuts
 * - StreamingIndicator — animated streaming feedback
 * - SelectionToolbar — text selection actions
 * - TipsList — displays saved tips for the node
 * - EngineStatusIndicator — shows active engine (Story 3-9)
 * - QuotaExhaustedBanner — quota degradation UI (Story 3-10)
 * - RecoveryBanner — crash recovery UI (Story 3-11)
 */

import { useEffect, useRef, useCallback, useState } from 'react';
import type { Node } from '@xyflow/react';
import { useChatStore, type EdgeContext } from '../stores/chat-store';
import { MessageBubble } from './chat/MessageBubble';
import { InputBar } from './chat/InputBar';
import { StreamingIndicator } from './chat/StreamingIndicator';
import { SelectionToolbar } from './chat/SelectionToolbar';
import { TipsList } from './chat/TipsList';
import { EngineStatusIndicator } from './chat/EngineStatusIndicator';
import { QuotaExhaustedBanner } from './chat/QuotaExhaustedBanner';
import { RecoveryBanner } from './chat/RecoveryBanner';
import { SkillSelector } from './chat/SkillSelector';
import { usePullToNode } from '../hooks/usePullToNode';

// ═══════════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════════

interface ChatPanelProps {
  /** Selected node (for normal mode). Null when in edge mode. */
  selectedNode?: Node | null;
  /** Edge context (for edge mode). Null when in normal mode. */
  edgeContext?: EdgeContext | null;
  onOpenSettings?: () => void;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Component
// ═══════════════════════════════════════════════════════════════════════════════

export function ChatPanel({ selectedNode, edgeContext, onOpenSettings }: ChatPanelProps) {
  // Story 4-1/4-2: Determine mode from props
  const chatMode = useChatStore((s) => s.chatMode);
  const currentEdge = useChatStore((s) => s.currentEdge);
  const isEdgeMode = chatMode === 'edge' && currentEdge !== null;

  // Derive display values based on mode
  const nodeId = isEdgeMode
    ? `edge_${currentEdge!.edgeId}`
    : selectedNode?.id ?? '';
  const displayTitle = isEdgeMode
    ? `${currentEdge!.sourceNodeName} \u2194 ${currentEdge!.targetNodeName}`
    : ((selectedNode?.data as Record<string, unknown>)?.title as string) || 'Untitled';

  // ── PullToNode hook (Fix 2: MVP #14) ─────────────────────────────────
  const { pullToNode } = usePullToNode();

  const handlePullToNode = useCallback(
    (selectedText: string) => {
      if (!nodeId || isEdgeMode) return;
      pullToNode(selectedText, nodeId);
    },
    [nodeId, isEdgeMode, pullToNode],
  );

  // ── Store bindings ────────────────────────────────────────────────────

  const messages = useChatStore((s) => s.messages);
  const isStreaming = useChatStore((s) => s.isStreaming);
  const engineUnavailable = useChatStore((s) => s.engineUnavailable);
  const waitingForFirstToken = useChatStore((s) => s.waitingForFirstToken);
  const hasMore = useChatStore((s) => s.hasMore);
  const switchNode = useChatStore((s) => s.switchNode);
  const switchToEdge = useChatStore((s) => s.switchToEdge);
  const loadMore = useChatStore((s) => s.loadMore);
  const sendMessage = useChatStore((s) => s.sendMessage);
  const clearHistory = useChatStore((s) => s.clearHistory);
  const quotaStatus = useChatStore((s) => s.quotaStatus);

  // ── SkillSelector state (Fix 3: MVP #13) ───────────────────────────
  const [skillSelectorVisible, setSkillSelectorVisible] = useState(false);
  const [skillSearchQuery, setSkillSearchQuery] = useState('');

  const handleSlashTrigger = useCallback((inputValue: string) => {
    if (inputValue.startsWith('/')) {
      setSkillSelectorVisible(true);
      setSkillSearchQuery(inputValue.slice(1)); // strip leading '/'
    } else {
      // '/' removed from input — dismiss the selector
      setSkillSelectorVisible(false);
      setSkillSearchQuery('');
    }
  }, []);

  const handleSkillSelect = useCallback(
    (command: string) => {
      setSkillSelectorVisible(false);
      setSkillSearchQuery('');
      // Send the skill command as a chat message
      sendMessage(command, displayTitle);
    },
    [sendMessage, displayTitle],
  );

  const handleSkillDismiss = useCallback(() => {
    setSkillSelectorVisible(false);
    setSkillSearchQuery('');
  }, []);

  // ── Refs ──────────────────────────────────────────────────────────────

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const sentinelRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  // ── Switch node/edge on selection change ──────────────────────────────

  useEffect(() => {
    if (edgeContext) {
      switchToEdge(edgeContext);
    } else if (selectedNode) {
      switchNode(selectedNode.id);
    }
  }, [edgeContext, selectedNode, switchNode, switchToEdge]);

  // ── Auto-scroll to bottom on new messages ─────────────────────────────

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // ── Lazy loading: IntersectionObserver on top sentinel ────────────────

  useEffect(() => {
    const sentinel = sentinelRef.current;
    const container = scrollContainerRef.current;
    if (!sentinel || !container || !hasMore) return;

    const observer = new IntersectionObserver(
      (entries) => {
        const entry = entries[0];
        if (entry && entry.isIntersecting) {
          // Save scroll position before loading
          const prevScrollHeight = container.scrollHeight;
          loadMore().then(() => {
            // Restore scroll position after prepending older messages
            const newScrollHeight = container.scrollHeight;
            container.scrollTop = newScrollHeight - prevScrollHeight;
          });
        }
      },
      { root: container, threshold: 0.1 },
    );

    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [hasMore, loadMore]);

  // ── Send handler ──────────────────────────────────────────────────────

  const handleSend = useCallback(
    (text: string) => {
      sendMessage(text, displayTitle);
    },
    [sendMessage, displayTitle],
  );

  // ── Clear handler ─────────────────────────────────────────────────────

  const handleClear = useCallback(() => {
    clearHistory();
  }, [clearHistory]);

  // ── Open settings handler (for quota degradation) ─────────────────────

  const handleOpenSettings = useCallback(() => {
    if (onOpenSettings) {
      onOpenSettings();
    }
  }, [onOpenSettings]);

  // ── Render ────────────────────────────────────────────────────────────

  return (
    <div className="flex flex-col h-full">
      {/* Header — Story 3-9: Engine status indicator, Story 4-1: Edge mode header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-gray-200 shrink-0">
        <div className="flex items-center gap-2 min-w-0">
          <h3 className="text-sm font-medium text-gray-700 truncate">
            {isEdgeMode ? (
              <span title="Edge Dialog">
                <span className="text-blue-500">Edge:</span> {displayTitle}
              </span>
            ) : (
              <>Chat: {displayTitle}</>
            )}
          </h3>
          <EngineStatusIndicator />
        </div>
        {messages.length > 0 && (
          <button
            onClick={handleClear}
            className="text-xs text-gray-400 hover:text-red-500 transition-colors shrink-0 ml-2"
            title="Clear chat history"
          >
            Clear
          </button>
        )}
      </div>

      {/* Engine unavailable banner */}
      {engineUnavailable && (
        <div className="px-3 py-2 bg-amber-50 border-b border-amber-200 shrink-0">
          <p className="text-xs text-amber-700">
            Claude Code not available. Run via Tauri desktop app to enable AI chat.
          </p>
        </div>
      )}

      {/* Story 3-11: Crash recovery banner */}
      <RecoveryBanner nodeTitle={displayTitle} />

      {/* Story 3-10: Quota exhaustion banner */}
      {quotaStatus === 'exhausted' && (
        <QuotaExhaustedBanner onOpenSettings={handleOpenSettings} />
      )}

      {/* Messages list */}
      <div
        ref={scrollContainerRef}
        className="flex-1 overflow-y-auto px-3 py-3 space-y-3"
      >
        {/* Lazy loading sentinel — triggers loadMore when visible */}
        {hasMore && (
          <div ref={sentinelRef} className="flex justify-center py-2">
            <span className="text-xs text-gray-300">Loading older messages...</span>
          </div>
        )}

        {/* Empty state — Story 4-1: different prompt for edge mode */}
        {messages.length === 0 && !hasMore && (
          <div className="flex items-center justify-center h-full">
            <p className="text-sm text-gray-400 text-center">
              {isEdgeMode
                ? `Discuss the relationship between "${currentEdge!.sourceNodeName}" and "${currentEdge!.targetNodeName}"`
                : <>Ask anything about &quot;{displayTitle}&quot;</>
              }
            </p>
          </div>
        )}

        {/* Message bubbles */}
        {messages.map((msg) => (
          <MessageBubble key={msg.id} message={msg} />
        ))}

        {/* Streaming indicator */}
        {isStreaming && (
          <StreamingIndicator waitingForFirstToken={waitingForFirstToken} />
        )}

        {/* Scroll anchor */}
        <div ref={messagesEndRef} />
      </div>

      {/* Tips section (collapsible, below messages) — only in node mode */}
      {!isEdgeMode && (
        <div className="shrink-0 border-t border-gray-100 px-3 py-2 max-h-40 overflow-y-auto">
          <TipsList nodeId={nodeId} />
        </div>
      )}

      {/* SkillSelector popup — appears on '/' trigger (Fix 3: MVP #13) */}
      {skillSelectorVisible && (
        <SkillSelector
          query={skillSearchQuery}
          onSelect={handleSkillSelect}
          onDismiss={handleSkillDismiss}
        />
      )}

      {/* Input bar — disabled when quota exhausted (Story 3-10 AC-4) */}
      <InputBar
        isStreaming={isStreaming}
        engineUnavailable={engineUnavailable}
        nodeTitle={displayTitle}
        onSend={handleSend}
        onSlashTrigger={handleSlashTrigger}
        quotaExhausted={quotaStatus === 'exhausted'}
      />

      {/* Text selection toolbar (floating, appears on text select) — only in node mode */}
      {!isEdgeMode && (
        <SelectionToolbar nodeId={nodeId} onPullToNode={handlePullToNode} />
      )}
    </div>
  );
}

// obsidian-canvas-learning/src/components/chat/ChatPanel.svelte
<!--
  Canvas Learning System - Chat Panel
  Story 3.3: ChatPanel UI (AC-1 through AC-6, Tasks 1-6)
  Story 3.4: Learning context auto-injection (AC-3, Task 4)
  Story 3.5: Skill command integration (AC-1/AC-2, Task 5)

  Main conversation UI for a single canvas node.
  Three-mode design: 'chat' | 'exam' | 'edge' (only 'chat' in this story).
  Integrates MessageBubble, InputBar, StreamingIndicator, and SkillSelector.
-->
<script lang="ts">
  import { onMount } from 'svelte';
  import type { App } from 'obsidian';
  import MessageBubble from './MessageBubble.svelte';
  import InputBar from './InputBar.svelte';
  import StreamingIndicator from './StreamingIndicator.svelte';
  import SkillSelector from './SkillSelector.svelte';
  import QuotaExhausted from './QuotaExhausted.svelte';
  import RecoveryBanner from './RecoveryBanner.svelte';
  import { chatState, type ChatMessage } from '../../stores/chat-state.svelte';
  import { skillRegistry, type Skill } from '../../services/skill-registry';
  import { MessageStore } from '../../services/message-store';

  let {
    mode = 'chat',
    nodeId,
    nodeName = '',
    app,
  }: {
    mode?: 'chat' | 'exam' | 'edge';
    nodeId: string;
    nodeName?: string;
    app: App;
  } = $props();

  let messageListEl: HTMLDivElement | undefined = $state(undefined);
  let inputBarRef: InputBar | undefined = $state(undefined);
  let showSkillSelector = $state(false);
  let skillFilterQuery = $state('');
  let thinkingTimeout: ReturnType<typeof setTimeout> | null = null;
  let showThinking = $state(false);
  let messageStore: MessageStore | null = null;
  let historyLoaded = $state(false);
  let allHistoryLoaded = $state(false);
  let loadingMore = $state(false);
  let sentinelEl: HTMLDivElement | undefined = $state(undefined);
  let observer: IntersectionObserver | null = null;

  const INITIAL_LOAD_LIMIT = 50;
  const PAGE_SIZE = 50;
  let loadedOffset = 0;

  // Reactive bindings to chatState
  let messages = $derived(chatState.messages);
  let status = $derived(chatState.status);
  let isStreaming = $derived(status === 'streaming');
  let lastError = $derived(chatState.lastError);

  // Story 3.9: Engine type indicator
  let activeEngineType = $derived(chatState.activeEngineType);
  // Story 3.10: Quota status
  let quotaStatus = $derived(chatState.quotaStatus);
  // Story 3.11: Recovery status
  let recoveryStatus = $derived(chatState.recoveryStatus);

  // Story 4.1: Chat mode and Edge context
  let chatMode = $derived(chatState.chatMode);
  let currentEdge = $derived(chatState.currentEdge);

  /**
   * Story 4.1 AC-3: Header title based on chat mode.
   * - 'chat': node name
   * - 'edge': "A ↔ B"
   * - 'exam': exam status (future)
   */
  let headerTitle = $derived.by(() => {
    if (chatMode === 'edge' && currentEdge) {
      return `${currentEdge.sourceNodeName} ↔ ${currentEdge.targetNodeName}`;
    }
    return nodeName || '对话';
  });

  // Skills list from registry
  let skills = $derived(skillRegistry.skills);

  // AC-6: 2s timeout for "thinking" indicator
  $effect(() => {
    if (status === 'streaming') {
      if (thinkingTimeout) clearTimeout(thinkingTimeout);
      showThinking = true;
      thinkingTimeout = setTimeout(() => {
        // After 2s, showThinking stays true (the text changes from dots to "正在思考...")
      }, 2000);
    } else {
      if (thinkingTimeout) {
        clearTimeout(thinkingTimeout);
        thinkingTimeout = null;
      }
      showThinking = false;
    }
  });

  // Auto-scroll to bottom when new messages arrive
  $effect(() => {
    void messages.length;
    void status;
    scrollToBottom();
  });

  function scrollToBottom(): void {
    queueMicrotask(() => {
      if (messageListEl) {
        messageListEl.scrollTop = messageListEl.scrollHeight;
      }
    });
  }

  /** Send a message to the chat engine. */
  async function handleSend(message: string): Promise<void> {
    await chatState.sendMessage(message);

    // Persist messages after send+response cycle
    if (messageStore) {
      const msgs = chatState.messages;
      // Save last user message
      const lastUser = msgs.filter((m) => m.role === 'user').pop();
      if (lastUser) {
        await messageStore.saveMessage(nodeId, lastUser);
      }
      // Save last assistant message
      const lastAssistant = msgs.filter((m) => m.role === 'assistant').pop();
      if (lastAssistant) {
        await messageStore.saveMessage(nodeId, lastAssistant);
      }
    }
  }

  /** Handle skill selection from SkillSelector. */
  function handleSkillSelect(skill: Skill): void {
    showSkillSelector = false;
    skillFilterQuery = '';
    inputBarRef?.setInputText(`/${skill.commandName} `);
  }

  function handleSlashTrigger(): void {
    showSkillSelector = true;
    skillFilterQuery = '';
  }

  function handleSlashInput(query: string): void {
    skillFilterQuery = query;
    if (!showSkillSelector) {
      showSkillSelector = true;
    }
  }

  function handleSkillSelectorClose(): void {
    showSkillSelector = false;
    skillFilterQuery = '';
  }

  /** AC-4: Load history from SQLite on mount. */
  async function loadHistory(): Promise<void> {
    if (!messageStore) return;

    const history = await messageStore.loadMessages(nodeId, INITIAL_LOAD_LIMIT, 0);
    if (history.length > 0) {
      // History is returned newest-first; reverse for display
      const reversed = history.reverse();
      chatState.loadHistory(reversed);
      loadedOffset = history.length;
    }
    if (history.length < INITIAL_LOAD_LIMIT) {
      allHistoryLoaded = true;
    }
    historyLoaded = true;
  }

  /** Lazy load more history when scrolling to top. */
  async function loadMoreHistory(): Promise<void> {
    if (loadingMore || allHistoryLoaded || !messageStore) return;
    loadingMore = true;

    const older = await messageStore.loadMessages(nodeId, PAGE_SIZE, loadedOffset);
    if (older.length > 0) {
      const reversed = older.reverse();
      chatState.prependHistory(reversed);
      loadedOffset += older.length;
    }
    if (older.length < PAGE_SIZE) {
      allHistoryLoaded = true;
    }
    loadingMore = false;
  }

  onMount(() => {
    // Initialize message store for history persistence
    const pluginDataDir = (app as unknown as { vault: { adapter: { basePath: string } } })
      .vault.adapter.basePath;
    messageStore = new MessageStore(pluginDataDir);

    // Open the node chat (switches state + restores cache)
    chatState.openNodeChat(nodeId);

    // Load persisted history
    loadHistory();

    // Load skills from the commands directory
    const vaultPath = (app as unknown as { vault: { adapter: { basePath: string } } })
      .vault.adapter.basePath;
    skillRegistry.loadSkills(vaultPath);

    // Set up IntersectionObserver for lazy-loading older messages
    if (sentinelEl) {
      observer = new IntersectionObserver(
        (entries) => {
          if (entries[0]?.isIntersecting && historyLoaded) {
            loadMoreHistory();
          }
        },
        { root: messageListEl, threshold: 0.1 },
      );
      observer.observe(sentinelEl);
    }

    return () => {
      if (observer) {
        observer.disconnect();
        observer = null;
      }
      if (thinkingTimeout) {
        clearTimeout(thinkingTimeout);
      }
    };
  });
</script>

<div class="cl-chat-panel">
  <!-- Header (Story 3.9 AC-4.1: engine type indicator, Story 4.1 AC-3: edge mode) -->
  <div class="cl-chat-panel__header" class:cl-chat-panel__header--edge={chatMode === 'edge'}>
    <div class="cl-chat-panel__header-title">
      <!-- Story 4.1 AC-3: Edge mode shows "A ↔ B" with edge icon -->
      {#if chatMode === 'edge'}
        <span class="cl-chat-panel__edge-icon">🔗</span>
      {/if}
      {headerTitle}
    </div>
    <div class="cl-chat-panel__header-status">
      <!-- Story 4.1: Mode label -->
      {#if chatMode === 'edge'}
        <span class="cl-chat-panel__mode-label cl-chat-panel__mode-label--edge">
          Edge Q&A
        </span>
      {/if}
      <!-- Story 3.9: Engine type label -->
      <span
        class="cl-chat-panel__engine-label"
        class:cl-chat-panel__engine-label--fallback={activeEngineType === 'api-key'}
      >
        {activeEngineType === 'claude-code' ? 'Claude Code' : 'API Key'}
      </span>
      {#if isStreaming}
        <span class="cl-chat-panel__status-dot cl-chat-panel__status-dot--active"></span>
        <span>对话中</span>
      {:else if lastError}
        <span class="cl-chat-panel__status-dot cl-chat-panel__status-dot--error"></span>
        <span>错误</span>
      {:else}
        <span class="cl-chat-panel__status-dot cl-chat-panel__status-dot--idle"></span>
        <span>就绪</span>
      {/if}
    </div>
  </div>

  <!-- Messages List -->
  <div class="cl-chat-panel__messages" bind:this={messageListEl}>
    <!-- Story 3.11: Recovery banner at top of message list -->
    {#if recoveryStatus !== 'idle'}
      <RecoveryBanner
        status={recoveryStatus}
        onRetry={() => { /* Manual retry handled via chatState / crashRecovery */ }}
      />
    {/if}

    <!-- Sentinel for lazy-loading older messages -->
    <div bind:this={sentinelEl} class="cl-chat-panel__sentinel">
      {#if loadingMore}
        <span class="cl-chat-panel__loading-more">加载更多...</span>
      {/if}
    </div>

    {#if messages.length === 0 && historyLoaded}
      <div class="cl-chat-panel__empty">
        {#if chatMode === 'edge' && currentEdge}
          <!-- Story 4.1: Edge mode empty state -->
          <p>讨论连线关系</p>
          <p class="cl-chat-panel__empty-hint">
            {currentEdge.sourceNodeName} ↔ {currentEdge.targetNodeName}
          </p>
          <p class="cl-chat-panel__empty-hint">发送消息开始讨论为什么连接这两个概念</p>
        {:else}
          <p>开始你的学习对话</p>
          <p class="cl-chat-panel__empty-hint">输入 / 查看可用技能</p>
        {/if}
      </div>
    {/if}

    {#each messages as msg (msg.id)}
      <MessageBubble
        message={msg}
        {app}
        sourcePath=""
        isStreaming={isStreaming && msg === messages[messages.length - 1] && msg.role === 'assistant'}
      />
    {/each}

    {#if isStreaming && (messages.length === 0 || messages[messages.length - 1]?.role === 'user')}
      <div class="cl-chat-bubble cl-chat-bubble-agent">
        {#if showThinking}
          <div class="cl-chat-panel__thinking">正在思考...</div>
        {/if}
        <StreamingIndicator />
      </div>
    {/if}

    {#if lastError}
      <div class="cl-chat-panel__error">
        {lastError.message}
      </div>
    {/if}
  </div>

  <!-- Input Area / Quota Exhausted (Story 3.10 AC-3) -->
  {#if quotaStatus === 'exhausted'}
    <QuotaExhausted
      onDismiss={() => chatState.setQuotaAvailable()}
      onSwitchApiKey={() => {
        // Open Obsidian settings for API Key configuration
        (app as any).setting?.open();
      }}
    />
  {:else}
    <div class="cl-chat-panel__input-wrapper">
      {#if showSkillSelector}
        <SkillSelector
          {skills}
          filterQuery={skillFilterQuery}
          onSelect={handleSkillSelect}
          onClose={handleSkillSelectorClose}
        />
      {/if}
      <InputBar
        bind:this={inputBarRef}
        disabled={isStreaming || quotaStatus === 'checking'}
        placeholder={quotaStatus === 'checking' ? '正在检测额度...' : undefined}
        onSend={handleSend}
        onSlashTrigger={handleSlashTrigger}
        onSlashInput={handleSlashInput}
      />
    </div>
  {/if}
</div>

<style>
  .cl-chat-panel {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--background-primary);
    color: var(--text-normal);
    font-family: var(--font-interface);
  }

  /* Header */
  .cl-chat-panel__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 12px;
    border-bottom: 1px solid var(--background-modifier-border);
    flex-shrink: 0;
  }

  .cl-chat-panel__header-title {
    font-weight: 600;
    font-size: 0.95em;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .cl-chat-panel__header-status {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: 0.78em;
    color: var(--text-muted);
  }

  /* Story 3.9: Engine type label */
  .cl-chat-panel__engine-label {
    padding: 1px 6px;
    border-radius: 3px;
    font-size: 0.85em;
    background: var(--background-modifier-success, rgba(76, 175, 80, 0.12));
    color: var(--text-success, #4caf50);
    margin-right: 4px;
  }

  .cl-chat-panel__engine-label--fallback {
    background: var(--background-modifier-error-hover, rgba(226, 185, 61, 0.12));
    color: var(--text-warning, #e2b93d);
  }

  .cl-chat-panel__status-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
  }

  .cl-chat-panel__status-dot--idle {
    background: var(--color-green, #4caf50);
  }

  .cl-chat-panel__status-dot--active {
    background: var(--interactive-accent);
    animation: cl-pulse 1.5s infinite;
  }

  .cl-chat-panel__status-dot--error {
    background: var(--color-red, #f44336);
  }

  @keyframes cl-pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.4; }
  }

  /* Messages */
  .cl-chat-panel__messages {
    flex: 1;
    overflow-y: auto;
    padding: 12px;
    display: flex;
    flex-direction: column;
  }

  .cl-chat-panel__sentinel {
    min-height: 1px;
    flex-shrink: 0;
  }

  .cl-chat-panel__loading-more {
    display: block;
    text-align: center;
    font-size: 0.8em;
    color: var(--text-faint);
    padding: 4px 0;
  }

  .cl-chat-panel__empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex: 1;
    color: var(--text-muted);
    text-align: center;
    gap: 4px;
  }

  .cl-chat-panel__empty p {
    margin: 0;
    font-size: 0.95em;
  }

  .cl-chat-panel__empty-hint {
    font-size: 0.82em !important;
    color: var(--text-faint);
  }

  .cl-chat-panel__thinking {
    font-size: 0.82em;
    color: var(--text-muted);
    padding: 4px 12px 0;
  }

  .cl-chat-panel__error {
    background: rgba(244, 67, 54, 0.1);
    color: var(--color-red, #f44336);
    padding: 8px 12px;
    border-radius: var(--radius-s, 4px);
    font-size: 0.85em;
    margin-top: 8px;
  }

  /* Input wrapper: positioned relatively so SkillSelector can anchor above */
  .cl-chat-panel__input-wrapper {
    position: relative;
    flex-shrink: 0;
  }

  /* Story 4.1: Edge mode header styling */
  .cl-chat-panel__header--edge {
    border-bottom-color: var(--interactive-accent);
  }

  .cl-chat-panel__edge-icon {
    margin-right: 4px;
    font-size: 0.9em;
  }

  .cl-chat-panel__mode-label {
    padding: 1px 6px;
    border-radius: 3px;
    font-size: 0.85em;
    margin-right: 4px;
  }

  .cl-chat-panel__mode-label--edge {
    background: var(--interactive-accent-hover, rgba(0, 102, 204, 0.12));
    color: var(--interactive-accent);
  }
</style>
